// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tylcqsruekcmuvyeohfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bGNxc3J1ZWtjbXV2eWVvaGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzU1NjMsImV4cCI6MjA1Njk1MTU2M30.MLeCGyuU8p5iWm4zeNP-DE3PJfOwZy-dA3wJKez5g20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);